2016-09-04 19:43:06 [scrapy] INFO: Scrapy 1.1.2 started (bot: auctionsSp)
2016-09-04 19:43:06 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'auctionsSp.spiders', 'FEED_URI': 'file:///Users/sabbidis/python/auctionsSp/items/auctionsSp/CourtAuctions/03bb111972c711e684670026bb5bbf98.jl', 'LOG_LEVEL': 'INFO', 'SPIDER_MODULES': ['auctionsSp.spiders'], 'BOT_NAME': 'auctionsSp', 'USER_AGENT': 'BlackBerry8330/4.3.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 VendorID/105', 'LOG_FILE': 'logs/auctionsSp/CourtAuctions/03bb111972c711e684670026bb5bbf98.log', 'DOWNLOAD_DELAY': 1}
2016-09-04 19:43:06 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2016-09-04 19:43:06 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'auctionsSp.middleware.CustomUserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-09-04 19:43:06 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-09-04 19:43:06 [scrapy] INFO: Enabled item pipelines:
['auctionsSp.pipelines.MongoPipeline']
2016-09-04 19:43:06 [scrapy] INFO: Spider opened
2016-09-04 19:43:06 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-09-04 19:43:11 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=19',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'11/01/2017',
 'debtor_name': u'CITY NEWS AE',
 'offer_price': u'794504.66',
 'publishedDateField': u'13/06/2016 13:09:52',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'9BXNXRmXc2',
 'vat_auctioneer': u'043996253',
 'vat_number': u'094264816'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:29 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=999',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0399\u03c9\u03ac\u03bd\u03bd\u03b7\u03c2 \u03a0\u0391\u03a0\u0391\u03aa\u03a9\u0391\u039d\u039d\u039f\u03a5',
 'offer_price': u'30000.00',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'Is1lo9SeTp',
 'vat_auctioneer': u'079243150',
 'vat_number': u'046316860'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:30 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=997',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u0398\u0395\u039f\u0394\u03a9\u03a1\u039f\u03a3 \u039c\u0395\u039b\u0399\u0391\u0394\u0397\u03a3 \u039a\u039b\u03a0',
 'offer_price': u'355000.00',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'BNEFE03W8k',
 'vat_auctioneer': u'094014250',
 'vat_number': u'014025890'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:33 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=995',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0391\u0399\u039a\u0391\u03a4\u0395\u03a1\u0399\u039d\u0397 \u03a7\u0391\u03a4\u0396\u0397\u039b\u0391\u0396\u0391\u03a1\u0399\u0394\u039f\u03a5 \u03a4\u039f\u03a5 \u0393\u0395\u03a9\u03a1\u0393\u0399\u039f\u03a5, \u0394\u0397\u039c\u0397\u03a4\u03a1\u0391 \u03a7\u0397\u03a1\u0391 \u0393\u0395\u03a9\u03a1\u0393\u0399\u039f\u03a5 \u03a7\u0391\u03a4\u0396\u0397\u039b\u0391\u0396\u0391\u03a1\u0399\u0394\u0397, \u0393\u0395\u03a9\u03a1\u0393\u0399\u039f\u03a3 \u03a7\u0391\u03a4\u0396\u0397\u039b\u0391\u0396\u0391\u03a1\u0399\u0394\u0397\u03a3 \u03a4\u039f\u03a5 \u0393\u0395\u03a9\u03a1\u0393\u0399\u039f\u03a5',
 'offer_price': u'',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'cwPyxylqPD',
 'vat_auctioneer': u'094014249',
 'vat_number': u'036012961'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:36 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=993',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\xab\u039a\u03a1\u0395\u03a3\u03a4\u0391 \u0395\u039c\u03a0\u039f\u03a1\u0399\u0391 \u039a\u0391\u0399 \u0392\u0399\u039f\u039c\u0397\u03a7\u0391\u039d\u0399\u0391 \u0395\u0399\u0394\u03a9\u039d \u03a5\u0393\u0399\u0395\u0399\u039d\u0397\u03a3 \u039a\u0391\u0399 \u0395\u03a0\u0399\u03a0\u039b\u03a9\u039d \u039a\u039f\u03a5\u0396\u0399\u039d\u0391\u03a3 \u0391\u039d\u03a9\u039d\u03a5\u039c\u0397 \u0395\u03a4\u0391\u0399\u03a1\u0395\u0399\u0391\xbb \u03ba\u03b1\u03b9 \u03c4\u03bf \u03b4.\u03c4. \xabCRESTILE \u0391.\u0395.\xbb',
 'offer_price': u'313788.00',
 'publishedDateField': u'02/09/2016 09:55:05',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'j5ZpovJ3W3',
 'vat_auctioneer': u'094014250',
 'vat_number': u'094284692'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:38 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=991',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0394\u0397\u039c\u0397\u03a4\u03a1\u0399\u039f\u03a3 \u039c\u03a0\u039f\u039d\u0399\u0391\u03a3 \u03c4\u03bf\u03c5 \u0393\u0395\u03a9\u03a1\u0393\u0399\u039f\u03a5',
 'offer_price': u'',
 'publishedDateField': u'02/09/2016 09:54:35',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'iPNZTmIuqu',
 'vat_auctioneer': u'094014250',
 'vat_number': u'051545036'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:41 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=989',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0393\u0399\u0391\u039d\u039d\u039f\u03a5\u039b\u0391\u03a3 \u039b\u039f\u03a4\u0396\u0399\u03a3\u03a4\u0399\u039a\u03a3 \u039c\u039f\u039d\u039f\u03a0\u03a1\u039f\u03a3\u03a9\u03a0\u0397 \u0395\u03a4\u0391\u0399\u03a1\u0395\u0399\u0391 \u03a0\u0395\u03a1\u0399\u039f\u03a1\u0399\u03a3\u039c\u0395\u039d\u0397\u03a3 \u0395\u03a5\u0398\u03a5\u039d\u0397\u03a3',
 'offer_price': u'2592340.00',
 'publishedDateField': u'02/09/2016 09:53:59',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'wROKoKyceb',
 'vat_auctioneer': u'094014250',
 'vat_number': u'999252326'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:43 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=987',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u039a\u03c5\u03c0\u03b1\u03c1\u03b9\u03c3\u03c3\u03bf\u03cd\u03bb\u03b1 \u03c3\u03c5\u03b6. \u03a6\u03c9\u03c4\u03af\u03bf\u03c5 \u0393\u03b5\u03c1\u03b1\u03ba\u03af\u03c4\u03b7, \u03c4\u03bf \u03b3\u03ad\u03bd\u03bf\u03c2 \u039c\u03b7\u03bd\u03ac \u03ba\u03b1\u03b9 \u0391\u03b9\u03ba\u03b1\u03c4\u03b5\u03c1\u03af\u03bd\u03b7\u03c2 \u03a3\u03bf\u03c6\u03af\u03bf\u03c5, \u03a6\u03ce\u03c4\u03b9\u03bf\u03c2 \u0393\u03b5\u03c1\u03b1\u03ba\u03af\u03c4\u03b7\u03c2 \u03c4\u03bf\u03c5 \u03a0\u03bf\u03bb\u03c5\u03c7\u03c1\u03cc\u03bd\u03b7 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u0391\u03bb\u03af\u03ba\u03b7\u03c2, \u03a0\u03bf\u03bb\u03c5\u03c7\u03c1\u03cc\u03bd\u03b7\u03c2 \u0393\u03b5\u03c1\u03b1\u03ba\u03af\u03c4\u03b7\u03c2 \u03c4\u03bf\u03c5 \u03a6\u03c9\u03c4\u03af\u03bf\u03c5 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u039a\u03c5\u03c0\u03b1\u03c1\u03b9\u03c3\u03c3\u03bf\u03cd\u03bb\u03b1\u03c2',
 'offer_price': u'616494.00',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'fqfx0dHEZ2',
 'vat_auctioneer': u'094014250',
 'vat_number': u'045341232'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:46 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=985',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u039a\u03a5\u03a0\u0391\u03a1\u0399\u03a3\u03a3\u039f\u03a5\u039b\u0391 \u03c3\u03cd\u03b6\u03c5\u03b3\u03bf\u03c2 \u03a6\u03c9\u03c4\u03af\u03bf\u03c5 \u0393\u0395\u03a1\u0391\u039a\u0399\u03a4\u0397 \u03c4\u03bf \u03b3\u03ad\u03bd\u03bf\u03c2 \u039c\u03b7\u03bd\u03ac \u03ba\u03b1\u03b9 \u0391\u03b9\u03ba\u03b1\u03c4\u03b5\u03c1\u03af\u03bd\u03b7\u03c2 \u03a3\u039f\u03a6\u0399\u039f\u03a5, \u03a6\u03a9\u03a4\u0399\u039f\u03a3 \u0393\u0395\u03a1\u0391\u039a\u0399\u03a4\u0397\u03a3 \u03c4\u03bf\u03c5 \u03a0\u03bf\u03bb\u03c5\u03c7\u03c1\u03cc\u03bd\u03b7 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u0391\u03bb\u03af\u03ba\u03b7\u03c2, \u03a0\u039f\u039b\u03a5\u03a7\u03a1\u039f\u039d\u0397\u03a3 \u0393\u0395\u03a1\u0391\u039a\u0399\u03a4\u0397\u03a3 \u03c4\u03bf\u03c5 \u03a6\u03c9\u03c4\u03af\u03bf\u03c5 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u039a\u03c5\u03c0\u03b1\u03c1\u03b9\u03c3\u03c3\u03bf\u03cd\u03bb\u03b1\u03c2',
 'offer_price': u'616494.00',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'Iw4W3wgmV2',
 'vat_auctioneer': u'094014250',
 'vat_number': u'045341232'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:47 [scrapy] ERROR: Error caught on signal handler: <bound method ?.item_scraped of <scrapy.extensions.feedexport.FeedExporter object at 0x103bdc350>>
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/scrapy/extensions/feedexport.py", line 211, in item_scraped
    slot.exporter.export_item(item)
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/scrapy/exporters.py", line 90, in export_item
    itemdict = dict(self._get_serialized_fields(item))
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/scrapy/exporters.py", line 65, in _get_serialized_fields
    field_iter = six.iterkeys(item)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six-1.9.0-py2.7.egg/six.py", line 570, in iterkeys
    return iter(d.iterkeys(**kw))
AttributeError: 'NoneType' object has no attribute 'iterkeys'
2016-09-04 19:43:50 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=983',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0393\u0399\u0391\u039d\u039d\u039f\u03a5\u039b\u0391\u03a3 \u039a\u03a9\u039d\u03a3\u03a4\u0391\u039d\u03a4\u0399\u039d\u039f\u03a3 \u03c4\u03bf\u03c5 \u0398\u03b5\u03bf\u03c7\u03ac\u03c1\u03b7 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u0391\u03b9\u03ba\u03b1\u03c4\u03b5\u03c1\u03af\u03bd\u03b7\u03c2',
 'offer_price': u'285855.00',
 'publishedDateField': u'02/09/2016 09:53:27',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'BejS0WeEY3',
 'vat_auctioneer': u'094014250',
 'vat_number': u'037120540'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:53 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=981',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0393\u0399\u0391\u039d\u039d\u039f\u03a5\u039b\u0391\u03a3 \u0398\u0395\u039f\u03a7\u0391\u03a1\u0397\u03a3 \u03c4\u03bf\u03c5 \u039a\u03c9\u03bd/\u03bd\u03bf\u03c5 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u0396\u03b7\u03bd\u03bf\u03b2\u03af\u03b1\u03c2',
 'offer_price': u'408364.00',
 'publishedDateField': u'02/09/2016 09:52:57',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'TxcqVL9Smh',
 'vat_auctioneer': u'094014250',
 'vat_number': u'009622825'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:55 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=979',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0393\u0399\u0391\u039d\u039d\u039f\u03a5\u039b\u0391\u03a3 \u0398\u0395\u039f\u03a7\u0391\u03a1\u0397\u03a3 \u03c4\u03bf\u03c5 \u039a\u03c9\u03bd/\u03bd\u03bf\u03c5 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u0396\u03b7\u03bd\u03bf\u03b2\u03af\u03b1\u03c2',
 'offer_price': u'408364.00',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'3nSC7lGcOs',
 'vat_auctioneer': u'094014250',
 'vat_number': u'009622825'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:43:58 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=977',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u0393\u039a\u03a1\u0399\u03a4\u0396\u0391\u03a3 \u0391\u039b\u039a\u0399\u0392\u0399\u0391\u0394\u0397\u03a3',
 'offer_price': u'',
 'publishedDateField': u'01/09/2016 09:14:23',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'4IDNDulg9w',
 'vat_auctioneer': u'094014249',
 'vat_number': u'019937462'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:00 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=975',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0391\u039d\u03a4\u0399\u0393\u039f\u039d\u0397 \u039a\u039b\u0391\u03a5\u03a3\u0397 \u03c4\u03bf\u03c5 \u0394\u0397\u039c\u0397\u03a4\u03a1\u0399\u039f\u03a5',
 'offer_price': u'513992.00',
 'publishedDateField': u'01/09/2016 11:05:01',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'ZwbV7iI25f',
 'vat_auctioneer': u'094014250',
 'vat_number': u'053890896'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:03 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=973',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0392\u0391\u039b\u0391\u0392\u0391\u039d\u0397 \u039c\u0391\u03a1\u0399\u0391 \u03c4\u03bf\u03c5 \u0391\u03bd\u03ac\u03c1\u03b3\u03c5\u03c1\u03bf\u03c5 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u0395\u03c5\u03b3\u03b5\u03bd\u03af\u03b1\u03c2',
 'offer_price': u'944387.00',
 'publishedDateField': u'02/09/2016 09:52:20',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'9UHRrylM3E',
 'vat_auctioneer': u'094014250',
 'vat_number': u'070420988'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:05 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=971',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\xab\u039c\u0391\u03a1\u0392\u039f \u0391\u039d\u03a9\u039d\u03a5\u039c\u0397 \u0392\u0399\u039f\u039c\u0397\u03a7\u0391\u039d\u0399\u039a\u0397 \u039a\u0391\u0399 \u0395\u039c\u03a0\u039f\u03a1\u0399\u039a\u0397 \u0395\u03a4\u0391\u0399\u03a1\u0395\u0399\u0391 \u0395\u0399\u03a3\u0391\u0393\u03a9\u0393\u03a9\u039d, \u0394\u0399\u0391\u039d\u039f\u039c\u03a9\u039d \u039a\u0391\u0399 \u03a0\u0391\u03a1\u0391\u0393\u03a9\u0393\u0397\u03a3 \u2013 \u0395\u039c\u03a0\u039f\u03a1\u0399\u0391\u03a3 \u03a7\u0391\u03a1\u03a4\u039f\u03a5 \u039a\u0391\u0399 \u03a7\u0391\u03a1\u03a4\u039f\u039a\u0399\u0392\u03a9\u03a4\u0399\u03a9\u039d\xbb,',
 'offer_price': u'',
 'publishedDateField': u'02/09/2016 09:51:40',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'wAM4HtBIAF',
 'vat_auctioneer': u'094014250',
 'vat_number': u'094025450'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:06 [scrapy] INFO: Crawled 18 pages (at 18 pages/min), scraped 1 items (at 1 items/min)
2016-09-04 19:44:08 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=969',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'1) \u0393\u0395\u03a9\u03a1\u0393\u0399\u0391 \u039a\u039f\u039d\u03a4\u0396\u0391\u039c\u0391\u039d\u0397 \u03c4\u03bf\u03c5 \u039a\u03a9\u039d\u03a3\u03a4\u0391\u039d\u03a4\u0399\u039d\u039f\u03a5, 2)  \u0391\u0399\u039a\u0391\u03a4\u0395\u03a1\u0399\u039d\u0397 \u0392\u0399\u03a4\u0396\u0397\u039b\u0391\u0399\u039f\u03a5 \u03c4\u03bf\u03c5 \u0399\u03a9\u0391\u039d\u039d\u0397',
 'offer_price': u'49480.57',
 'publishedDateField': u'01/09/2016 09:17:03',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'XOWWGnY2A7',
 'vat_auctioneer': u'094014250',
 'vat_number': u'035994315'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:10 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=967',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u03a0\u0391\u039d\u0391\u0393\u0399\u03a9\u03a4\u0397\u03a3 \u0393\u0399\u0391\u039d\u039d\u0391\u039a\u039f\u03a3 \u03c4\u03bf\u03c5 \u03a7\u03b1\u03c1\u03b1\u03bb\u03ac\u03bc\u03c0\u03bf\u03c5\u03c2 \u03ba\u03b1\u03b9 \u03c4\u03b7\u03c2 \u039c\u03b1\u03c1\u03af\u03b1\u03c2',
 'offer_price': u'',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'S0nqHYYUlx',
 'vat_auctioneer': u'094014250',
 'vat_number': u'030983987'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:13 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=965',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\xab\u0394\u039f\u039c\u039f\u03a0\u039f\u039b\u0399\u03a3 S.P. \u03a4\u0395\u03a7\u039d\u0399\u039a\u0397 \u0391\u039d\u03a9\u039d\u03a5\u039c\u039f\u03a3 \u0395\u03a4\u0391\u0399\u03a1\u0395\u0399\u0391\xbb \u03ba\u03b1\u03b9 \u03c4\u03bf \u03b4.\u03c4. \xab\u0394\u039f\u039c\u039f\u03a0\u039f\u039b\u0399\u03a3 S.P.\xbb',
 'offer_price': u'',
 'publishedDateField': u'02/09/2016 09:51:08',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'xietv5Oflf',
 'vat_auctioneer': u'094014250',
 'vat_number': u'099971272'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:15 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=963',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u03a4\u03a3\u039f\u039a\u0391 \u039a\u039b\u0395\u039f\u039d\u0399\u039a\u0397 \u03c3\u03c5\u03b6. \u039d\u0399\u039a\u039f\u039b\u0391\u039f\u03a5 \u03c4\u03bf \u03b3\u03ad\u03bd\u03bf\u03c2 \u0395\u03a5\u03a3\u03a4\u03a1\u0391\u03a4\u0399\u039f\u03a5 \u03ba\u03b1\u03b9 \u0395\u03a5\u03a4\u03a5\u03a7\u0399\u0391\u03a3 \u039a\u0391\u03a6\u0391\u039b\u039f\u03a5\u039a\u039f\u03a5',
 'offer_price': u'',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'GYYQUVVZFY',
 'vat_auctioneer': u'094014250',
 'vat_number': u'047244821'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:15 [scrapy] INFO: Received SIGTERM, shutting down gracefully. Send again to force 
2016-09-04 19:44:15 [scrapy] INFO: Closing spider (shutdown)
2016-09-04 19:44:18 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=961',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'ALSAPO ENTERPRICES WORLD LTD',
 'offer_price': u'1740000.00',
 'publishedDateField': u'01/09/2016 09:16:39',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'SGEMy3RdHM',
 'vat_auctioneer': u'021446361',
 'vat_number': u'997325143'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:20 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=959',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u0391\u03b9\u03ba\u03b1\u03c4\u03b5\u03c1\u03af\u03bd\u03b7 \u03a0\u03b1\u03bd\u03c4\u03b5\u03bb\u03af\u03b4\u03b7 \u03ba\u03bb\u03c0',
 'offer_price': u'',
 'publishedDateField': u'01/09/2016 09:13:04',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'hWULvwcN7d',
 'vat_auctioneer': u'',
 'vat_number': u''}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:22 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u039a\u03b9\u03bd\u03b7\u03c4\u03ac'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=957',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'08/03/2017',
 'debtor_name': u'\u0399\u03a9\u0391\u039d\u039d\u0397\u03a3 \u03a4\u0396\u0397\u039c\u0391\u03a3 \u039a\u0391\u0399 \u03a3\u0399\u0391 \u039f\u0395',
 'offer_price': u'300.00',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'GXcMLFYNey',
 'vat_auctioneer': u'081542948',
 'vat_number': u'081648823'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:24 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=955',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'01/03/2017',
 'debtor_name': u'\u03a7\u03a1\u03a5\u03a3\u0391\u039d\u0398\u0397 \u03c3\u03c5\u03b6. \u0394\u0397\u039c\u0397\u03a4\u03a1\u0399\u039f\u03a5 \u03a1\u0391\u03a0\u03a4\u039f\u03a5',
 'offer_price': u'171000.00',
 'publishedDateField': u'02/09/2016 10:25:21',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'6M0nL0jrji',
 'vat_auctioneer': u'094014298',
 'vat_number': u'103473322'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:27 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=953',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'22/02/2017',
 'debtor_name': u'\u03a3\u03a0\u03a5\u03a1\u0399\u0394\u03a9\u039d \u03a7\u03a1\u0399\u03a3\u03a4\u039f\u0393\u039b\u039f\u03a5 \u0394\u0395\u03a3\u03a0\u039f\u0399\u039d\u0391  \u03a7\u03a1\u0399\u03a3\u03a4\u039f\u0393\u039b\u039f\u03a5',
 'offer_price': u'',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'goWDgG55iM',
 'vat_auctioneer': u'094014250',
 'vat_number': u'126594699'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:30 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=951',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'22/02/2017',
 'debtor_name': u'\u03a3\u03a0\u03a5\u03a1\u0399\u0394\u03a9\u039d \u03a7\u03a1\u0399\u03a3\u03a4\u039f\u0393\u039b\u039f\u03a5 \u0394\u0395\u03a3\u03a0\u039f\u0399\u039d\u0391  \u03a7\u03a1\u0399\u03a3\u03a4\u039f\u0393\u039b\u039f\u03a5',
 'offer_price': u'44337.15',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'4MeC9GUyxl',
 'vat_auctioneer': u'094014250',
 'vat_number': u'126594699'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:32 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=949',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'30/08/2016',
 'debtor_name': u'\u039c\u0399\u03a7\u0391\u0397\u039b \u03a7\u03a1\u0399\u03a3\u03a4\u039f\u0393\u039b\u039f\u03a5',
 'offer_price': u'66883.71',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'b4oppPPPfA',
 'vat_auctioneer': u'094014250',
 'vat_number': u'045698675'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:34 [scrapy] ERROR: Error processing {'asset_type': [<Selector xpath='text()' data=u'\u0391\u03ba\u03af\u03bd\u03b7\u03c4\u03b1'>],
 'auction_url': 'https://deltio.tnomik.gr/details?id=947',
 'auctioneer': [<Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>],
 'court': '',
 'dateTextField': u'22/02/2017',
 'debtor_name': u'\u039c\u0399\u03a7\u0391\u0397\u039b \u03a7\u03a1\u0399\u03a3\u03a4\u039f\u0393\u039b\u039f\u03a5',
 'offer_price': u'',
 'publishedDateField': u'\u0394\u03b5\u03bd \u03ad\u03c7\u03b5\u03b9 \u03b5\u03ba\u03c7\u03c9\u03c1\u03b7\u03b8\u03b5\u03af',
 'source': 'deltio.tnomik.gr',
 'unique_code': u'hcMpmh8aai',
 'vat_auctioneer': u'094014250',
 'vat_number': u'045698675'}
Traceback (most recent call last):
  File "/Users/sabbidis/Library/Python/2.7/lib/python/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "auctionsSp/pipelines.py", line 53, in process_item
    self.db[self.collection_name].insert(dict(item))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pymongo/collection.py", line 409, in insert
    gen(), check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: <Selector xpath='text()' data=u'\u03a8\u03a9\u03a6\u0399\u0394\u039f\u03a3'>
2016-09-04 19:44:34 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 27531,
 'downloader/request_count': 72,
 'downloader/request_method_count/GET': 72,
 'downloader/response_bytes': 524515,
 'downloader/response_count': 72,
 'downloader/response_status_count/200': 30,
 'downloader/response_status_count/301': 1,
 'downloader/response_status_count/302': 41,
 'dupefilter/filtered': 40,
 'finish_reason': 'shutdown',
 'finish_time': datetime.datetime(2016, 9, 4, 17, 44, 34, 658985),
 'item_scraped_count': 1,
 'log_count/ERROR': 29,
 'log_count/INFO': 9,
 'request_depth_max': 1,
 'response_received_count': 30,
 'scheduler/dequeued': 72,
 'scheduler/dequeued/memory': 72,
 'scheduler/enqueued': 1003,
 'scheduler/enqueued/memory': 1003,
 'start_time': datetime.datetime(2016, 9, 4, 17, 43, 6, 925964)}
2016-09-04 19:44:34 [scrapy] INFO: Spider closed (shutdown)
